FROM ubuntu:22.04
LABEL maintainer="Language Design Working Group <p4-design@lists.p4.org>"
LABEL description="Dockerfile used for building the asciidoc specification"

RUN  apt-get update && \
     apt-get install -y gnupg2 curl cmake flex libglib2.0-dev libcairo2-dev libpango1.0-dev libxml2-dev libwebp-dev libzstd-dev libgdk-pixbuf-2.0-dev

RUN  gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB &&\
     curl -sSL https://get.rvm.io | bash && \
     /bin/bash -l -c ". /usr/local/rvm/scripts/rvm && rvm install ruby-3.3.1" &&\
     /bin/bash -l -c ". /usr/local/rvm/scripts/rvm rvm use 3.3.1"

RUN gem install asciidoctor \
    gem install asciidoctor-pdf \
    gem install asciidoctor-bibtex \
    gem install asciidoctor-mathematical

# As of 2024-Jul-04, the official rouge repo has support for P4
# language syntax highlighting.
RUN git clone https://github.com/rouge-ruby/rouge \
    cd rouge \
    git log -n 1 | cat \
    gem build rouge.gemspec \ 
    gem install rouge-4.4.0.gem \
    gem install asciidoctor-bibtex \
    gem install asciidoctor-lists

VOLUME ["/usr/src/p4-spec"]
WORKDIR /usr/src/p4-spec