FROM ubuntu:22.04
LABEL maintainer="Language Design Working Group <p4-design@lists.p4.org>"
LABEL description="Dockerfile used for building the asciidoc specification"

VOLUME ["/usr/src/p4-spec"]
WORKDIR /usr/src/p4-spec

# add extra fonts for P4_14 look-alike
RUN ./p4-16/spec/install-asciidoctor-linux.sh

